@startuml
left to right direction
skinparam monochrome true
actor "Khách hàng" as KH
actor "Nhân viên quản lý" as QL
actor "Hướng dẫn viên" as HDV
rectangle "Quản lý công ty du lịch" {
 usecase "Tra cứu tour" as A
 usecase "Đăng ký tour" as B
 usecase "Đăng ký đoàn" as C
 usecase "Đăng ký chuyến lẻ" as D
 usecase "Đặt cọc / mua vé" as E
 usecase "Quản lý tour/chuyến" as F
 usecase "Quản lý khách hàng" as G
 usecase "Phân công hướng dẫn" as H
 usecase "Tính lương" as I
 usecase "Quyết toán / hủy" as J
 usecase "Khảo sát sau tour" as K
 }
KH -- A
KH -- B
KH -- K
QL -- F
QL -- G
QL -- B
QL -- H
QL -- I
QL -- J
HDV -- H
C -|> B
D -|> B
C ..> E : <<include>>
D ..> E : <<include>>
@enduml
